### ISSUE TITLE
Verificar autenticação via API Rest-Like quando usuário está inativo ou deletado

### ISSUE THREAD

**Issue by ronivalens** [titan-framework/core#10]
O serviço **auth** (api/auth) da **API Rest-Like** não está levando em consideração quando um usuário está marcado como **inativo** (_active = 0) ou **deletado** (_deleted = 1). Ao realizar a chamada do serviço, em alguma destas condições, o sistema autentica e libera o acesso e não retorna nenhuma mensagem de usuário inativo ou deletado.

**Comment by carromeu** [comment]
Os serviços de autenticação do Embrapa-Auth agora estão considerando o status do usuário (se ativo e/ou deletado).
