### ISSUE TITLE
Novas cores para mensagens 

### ISSUE THREAD

**Issue by fernandorech** [titan-framework/core#12]
A classe Message possui apenas 2 cores (verde e vermelho)

O ideal era que as cores pudessem se alteradas, havendo melhor interação com a aplicação

**Comment by carromeu** [comment]
O novo estilo de mensagens já está disponível na versão estável do framework. Foram criados 4 tipos: **SUCCESS**, **INFO**, **ALERT** e **WARNING**. Para utilizar:

```php
Message::singleton ()->add (Message::INFO, 'Sua mensagem informativa...');
```

Resultado:

![Novas cores para alertas.](https://lh4.googleusercontent.com/YIQV_SUg0b68E8ZaJOO63jMTMWHqzQE6EeV2128lS1Frf5fDwlMCQf6HAEI0GMPeLCq4JzgfMakBizoGMBHK=w1920-h917-rw)
