### ISSUE TITLE
Problemas com o componente Collection

### ISSUE THREAD

**Issue by ronivalens** [titan-framework/core#4]
Boa noite Camilo,

Após atualização do sistema estou enfrentando problemas no componente **Collection**. Ao clicar em **Salvar Item** o sistema fica travado na tela de carregando (imagem anexa) e não deixa o usuário prosseguir. O sistema se comporta da mesma maneira tanto no ambiente de produção quanto no de desenvolvimento.

Verifiquei no log e encontrei a seguinte descrição:

`[Wed Feb 01 21:10:54.190166 2017] [:error] [pid 9022] [client 191.184.206.232:37558] PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/titan/repos/type/global.Collection/_css.php:85) in /var/www/titan/class/Localization.php on line 124, referer: https://www.nilfit.com.br/manager/titan.php?target=body&toSection=access&toAction=log&itemId=0`

Versão: **3.17.01-693**

![loading](https://cloud.githubusercontent.com/assets/7474587/22533215/49e26eaa-e8cb-11e6-8b09-7fc7d367e73e.png)

**Comment by carromeu** [comment]
Roni, este tipo passou por uma grande manutenção evolutiva para possibilitar a edição de itens e o ordenamento da lista. Caso você esteja utilizando um tipo derivado do Collection, recomendo pegar o código do Collection anterior à revisão 658 e copiar os arquivos que não tenham sido sobreescritos para o seu tipo derivado (de tal forma que o Core carregue estes arquivos ao invés dos atuais).
Se não for este o caso, recomendo desabilitar o display_errors do seu php.ini e verificar no log o que de fato está ocorrendo. O erro que você postou é devido à impressão de output antes da função header, e não ajuda muito a encontrar o problema real.

**Comment by ronivalens** [comment]
Camilo, segui sua segunda recomendação e os arquivos de logs analisados em **/var/www/log/error.log**, **/var/log/apache2/error.log** e **/var/ww/app/manager/cache/log/log.201702** não apresentam nenhum erro no momento de inserir um item com o tipo _collection_. O único erro apresentado é o do navegador, o qual segue anexo.

![error_chrome](https://cloud.githubusercontent.com/assets/7474587/22622472/0c7abb66-eb1a-11e6-8623-d1a19de6bc71.png)

Obs: O erro também é apresentado no navegador Firefox.

**Comment by carromeu** [comment]
Roni, veja na pasta do tipo (em repos/type/global.Collection) se não existe conflito gerado pelo SVN ou GIT. Você está utilizando qual repositório?

**Comment by ronivalens** [comment]
Estou usando o repositório GIT. Não encontrei nenhum conflito na pasta!

![collection_directory](https://cloud.githubusercontent.com/assets/7474587/22631617/621e679a-ebef-11e6-9d1c-fed11328155f.png)

**Comment by carromeu** [comment]
Roni, aparentemente havia mesmo um erro no tipo. Algumas short open tags que passaram. Por favor, faça o teste novamente e veja se está Ok.

**Comment by ronivalens** [comment]
Camilo, sistema atualizado para a versão **3.17.02-696**, no entanto o erro ainda persiste!

![error](https://cloud.githubusercontent.com/assets/7474587/22673060/8fc832a8-ecb6-11e6-8920-6d92ace66316.png)

**Comment by carromeu** [comment]
Olá Roni, você ainda está tendo este problema?

Abraços,

Camilo

**Comment by ronivalens** [comment]
Olá Camilo,

O problema ainda persiste. O paliativo foi criar um novo tipo com os arquivos de uma versão antiga do core do **Collection**, o qual não estava apresentava o erro. No entanto, perdi as atualizações realizadas como a busca e ordenação dos itens.

![erro_collection_titan](https://cloud.githubusercontent.com/assets/7474587/24832418/e549ae9a-1c7d-11e7-9434-60d3419e53ef.png)
