### ISSUE TITLE
Problemas no toApi.php do Tipo FCK

### ISSUE THREAD

**Issue by mapsiva** [titan-framework/core#5]
Quando o campo  está com o valor vazio o seguinte warning é apresentado:

[WARNING] DOMDocument::loadHTML(): Empty string supplied as input [File: /var/www/titan/repos/type/global.Fck/toApi.php] [Line: 8]

Basta ajustar:

`if (!$field->useEmbeddedImages ())
	return $field->getValue ();`

Para:

`if (!$field->useEmbeddedImages () || empty($field->getValue ()))
	return $field->getValue ();`

**Comment by carromeu** [comment]
Corrigido, Marcio. Valeu pela dica!
