### ISSUE TITLE
Menu - Add class in interface/css/menu.css to backMenu Li element Option

### ISSUE THREAD

**Issue by fernandommota** [titan-framework/core#6]
Hi guys,

As a developer we would like to change the style applied to first option in Menu component. 

The follow screen show the problem when anybody change the default style of framework.

<img width="1279" alt="defaultview" src="https://cloud.githubusercontent.com/assets/263414/24628679/5c0ff306-1885-11e7-9f01-cc5d5b0e96af.png">

<img width="1274" alt="changedview" src="https://cloud.githubusercontent.com/assets/263414/24628690/64a23d26-1885-11e7-8c76-9e76c1a3fc1b.png">

Regards

**Comment by carromeu** [comment]
Hi Maia,

You try to use any like: "#menuBox div.menuMain li:first"?

Kind regards,

Camilo

**Comment by fernandommota** [comment]
Hi Camilo,

using your suggestion not works, but with the follow code yes:

```
#menuBox div.menuMain li:first-child{
	background-color: #006400 !important;
}
```

Is working only when i set the !important in CSS rule.

Example with default html generated and with CSS rule without !important:

![example_html_style](https://cloud.githubusercontent.com/assets/263414/24708876/2e17a0b8-19e6-11e7-9206-33072f4794b9.png)

Example with changed default html generated and with CSS rule without !important:

![example_removed_html_style](https://cloud.githubusercontent.com/assets/263414/24708879/325baea8-19e6-11e7-9dfa-d26c5bfddc8d.png)

Example with default html generated and with CSS rule with !important:

![example_html_style_and_css_important](https://cloud.githubusercontent.com/assets/263414/24708882/3627519a-19e6-11e7-9fc7-aa2a9b45463c.png)
