### ISSUE TITLE
Erro ao editar item tipo Select com search dentro de uma Collection

### ISSUE THREAD

**Issue by fernandommota** [titan-framework/core#8]
Olá,

Considerando uma collection com o seguinte search, a exibição da lista e ação de create funciona perfeitamente:
![screen shot 2017-06-29 at 09 58 01](https://user-images.githubusercontent.com/263414/27692357-7f8999c2-5cb4-11e7-93c9-ae54604d10e6.png)

Mas na ação de edição quando é realizado o clique sobre o botão para exibição da lista o mesmo não é exibido:
![screen shot 2017-06-29 at 09 58 17](https://user-images.githubusercontent.com/263414/27692333-6ec93fc0-5cb4-11e7-8303-dd17620ac210.png)

Analisando a função global.Select.showSearch(), pude verificar que a prpropriedade iframe.style.display na ação de edição finaliza setada com "none" e mesmo forçando seu valor para "block" a ação de "Salvar" não funciona corretamente.

```
global.Select.showSearch = function (fieldId)
{
	var iframe = $('_SEARCH_AT_SELECT_TYPE_' + fieldId);

	if (iframe.style.display == 'block')
		iframe.style.display = 'none';
	else
		iframe.style.display = 'block';
}
```

**Comment by carromeu** [comment]
Maia, obrigado por reportar este _bug_! A correção está na _branch_ "*master*" e será disponibilizada no próximo _release_.
