### ISSUE TITLE
Erro ao exibir propriedade color apos ação de criação ou edição em um tipo Select dentro de uma Collection

### ISSUE THREAD

**Issue by fernandommota** [titan-framework/core#9]
A propriedade "color" não é aplicada após uma ação de edição ou criação dentro de uma Collection usando o tipo Select.

Exemplo:
![screen shot 2017-06-29 at 10 23 46](https://user-images.githubusercontent.com/263414/27692633-2f677c9c-5cb5-11e7-89c9-e570a7af45ea.png)

**Comment by carromeu** [comment]
Maia, obrigado por reportar o _bug_! Este erro foi corrigido e já está na _branch_ "*master*". Será disponibilizado no próximo _release_.
